export interface FeedIngredient {
  id: string;
  nameAr: string;
  nameEn: string;
  category: "grain" | "fiber" | "protein" | "fat" | "supplement";
  dryMatterPercent: number;
  crudeProteinPercent: number;
  digestibleEnergyMcalKg: number;
  fiberPercent?: number;
}

export const FEED_INGREDIENTS: FeedIngredient[] = [
  {
    id: "barley",
    nameAr: "شعير",
    nameEn: "Barley",
    category: "grain",
    dryMatterPercent: 92,
    crudeProteinPercent: 11,
    digestibleEnergyMcalKg: 1.91,
    fiberPercent: 6.53,
  },
  {
    id: "corn",
    nameAr: "ذرة",
    nameEn: "Corn",
    category: "grain",
    dryMatterPercent: 90,
    crudeProteinPercent: 9.2,
    digestibleEnergyMcalKg: 1.84,
    fiberPercent: 2.6,
  },
  {
    id: "oats",
    nameAr: "شوفان",
    nameEn: "Oats",
    category: "grain",
    dryMatterPercent: 89,
    crudeProteinPercent: 11.5,
    digestibleEnergyMcalKg: 1.8,
    fiberPercent: 10,
  },
  {
    id: "wheat-bran",
    nameAr: "نخالة قمح",
    nameEn: "Wheat bran",
    category: "fiber",
    dryMatterPercent: 90,
    crudeProteinPercent: 16.8,
    digestibleEnergyMcalKg: 1.59,
    fiberPercent: 10.8,
  },
  {
    id: "alfalfa",
    nameAr: "برسيم / دريس حجاري",
    nameEn: "Alfalfa / hay",
    category: "fiber",
    dryMatterPercent: 90,
    crudeProteinPercent: 15,
    digestibleEnergyMcalKg: 1.9,
    fiberPercent: 25,
  },
  {
    id: "beet-pulp",
    nameAr: "ألياف بنجر",
    nameEn: "Beet pulp",
    category: "fiber",
    dryMatterPercent: 90,
    crudeProteinPercent: 9,
    digestibleEnergyMcalKg: 2.3,
    fiberPercent: 18,
  },
  {
    id: "soybean-meal",
    nameAr: "كسب فول صويا",
    nameEn: "Soybean meal",
    category: "protein",
    dryMatterPercent: 91,
    crudeProteinPercent: 44,
    digestibleEnergyMcalKg: 1.86,
  },
  {
    id: "cottonseed-meal",
    nameAr: "كسب قطن",
    nameEn: "Cottonseed meal",
    category: "protein",
    dryMatterPercent: 91.5,
    crudeProteinPercent: 38.6,
    digestibleEnergyMcalKg: 1.72,
  },
  {
    id: "linseed-meal",
    nameAr: "كسب كتان",
    nameEn: "Linseed meal",
    category: "protein",
    dryMatterPercent: 91,
    crudeProteinPercent: 30.2,
    digestibleEnergyMcalKg: 1.47,
  },
  {
    id: "sesame-meal",
    nameAr: "كسب سمسم",
    nameEn: "Sesame meal",
    category: "protein",
    dryMatterPercent: 93.7,
    crudeProteinPercent: 32.3,
    digestibleEnergyMcalKg: 1.74,
  },
  {
    id: "vegetable-oil",
    nameAr: "زيت نباتي",
    nameEn: "Vegetable oil",
    category: "fat",
    dryMatterPercent: 100,
    crudeProteinPercent: 0,
    digestibleEnergyMcalKg: 8.8,
  },
  {
    id: "molasses",
    nameAr: "مولاس",
    nameEn: "Molasses",
    category: "supplement",
    dryMatterPercent: 75,
    crudeProteinPercent: 5,
    digestibleEnergyMcalKg: 2.6,
  },
  {
    id: "balanced-mix-1",
    nameAr: "خلطة حبوب وبرسيم 11% بروتين",
    nameEn: "Grain and alfalfa mix, 11% protein",
    category: "supplement",
    dryMatterPercent: 90,
    crudeProteinPercent: 11,
    digestibleEnergyMcalKg: 2.5,
    fiberPercent: 10,
  },
  {
    id: "herbal-mix-2",
    nameAr: "خلطة أعشاب وفواكه 9.9% بروتين",
    nameEn: "Herbal fruit mix, 9.9% protein",
    category: "supplement",
    dryMatterPercent: 90,
    crudeProteinPercent: 9.9,
    digestibleEnergyMcalKg: 3.35,
    fiberPercent: 11,
  },
  {
    id: "fiber-mix-3",
    nameAr: "خلطة ألياف وحبوب 10.2% بروتين",
    nameEn: "Fiber grain mix, 10.2% protein",
    category: "supplement",
    dryMatterPercent: 90,
    crudeProteinPercent: 10.2,
    digestibleEnergyMcalKg: 2.51,
    fiberPercent: 12.6,
  },
];
